#!/bin/bash

if [ "`id -u`" != "0" ]
  then
    echo "This script can only run as root"
    exit 1
fi

if [ "${1}" = "" ]
 then
   echo "No argument, Usage: $0 <radish-file.bin>"
   exit 1
fi

check="true"
for ex in \
 echo pwd mktemp mount partclone.ext4 resize2fs fsck.ext4 bzip2
  do
    loc=`which "${ex}"`
    if [ "${loc}" = "" ]
      then
      echo "${ex} is missing"
      check="false"
    fi
  done

if [ "${check}" = "false" ]
  then
  echo "Some utilities are missing"
  exit 1
fi

set -e

unset LC_CTYPE LC_MESSAGES LC_ALL
export LANG=C

currdir=`pwd`
mountdir=`mktemp -d --tmpdir="${currdir}" radish-mount.XXXXXXXXXX`
imagefile=`mktemp --tmpdir="${currdir}" radish-image.XXXXXXXXXX`
bzip2 -dc "${1}" | partclone.ext4 -r -s - -W -O "${imagefile}"

echo "Expanding filesystem image..."

fsck.ext4 -f "${imagefile}"
resize2fs "${imagefile}" 2048M
mount -oloop "${imagefile}" "${mountdir}"
echo "${imagefile} is now mounted on ${mountdir}"
